name: 'Run Acceptance Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cli-assume-no-auth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
      - name: Run Test
        id: test
        run: yarn start assume test-role --headless || echo "::set-output name=returnCode::$?"
      - name: Check Return Code
        if: ${{ steps.test.outputs.returnCode != '10' }}
        run: |
          echo "The return code was ${{ steps.test.outputs.returnCode }}"
          exit 1
