name: 'Run Acceptance Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cli-assume-no-auth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn
      - name: Run Test
        run: yarn start assume test-role --headless
        continue-on-error: true
      - name: Set Output
        id: output
        run: echo "::set-output name=returnCode::$?"
      - name: Debug
        run: echo "${{ toJSON(steps.output) }}"
      # TODO check return code for accuracy
